### ISSUE TITLE
怎么用啊  -。-

### ISSUE THREAD

**Issue by jesse-tang-93** [tyrad/DengtaChromeExtension#1]

**Comment by tyrad** [comment]
使用方法： 
点击`扩展程序`，如图
<img width="721" alt="f" src="https://user-images.githubusercontent.com/12179671/37517619-02523b74-294d-11e8-8406-caba5af0f925.png">

勾选`开发者模式`，再点击`加载已经解压的扩展程序`，随后选择`DengtaChromeExtension/DengtaChromeExtension `文件夹就可以了
<img width="721" alt="f2" src="https://user-images.githubusercontent.com/12179671/37517674-200829da-294d-11e8-919d-acde1b90ae75.png">
