### ISSUE TITLE
遇到一个问题，答题完毕不会自动停止

### ISSUE THREAD

**Issue by ToQuery** [tyrad/DengtaChromeExtension#2]
答完20个题目后，不会自动停止（有可能没等到程序作出响应，我鼠标就去手动点击前面的第5道题了），然后程序就不会停止了。
并且会把已经做完题目的选项取消勾选。

**Comment by tyrad** [comment]
这个东西我写的比较仓促,可能很多情况没有考虑全。 

思路是匹配答案，然后“点击”答案选项，如果已经选择过了，再次选择可能就反选了(多选题型)。   程序不会自动停止可能是第20题没有匹配到答案，结束条件没有做这层判断。

我考虑下月答题的时候修复这些问题吧。

**Comment by ToQuery** [comment]
OK

**Comment by ToQuery** [comment]
来催更了。。。

**Comment by tyrad** [comment]
更上了。 不过貌似题库有点问题，不是完全匹配

**Comment by XTTGO** [comment]
今天早上用模拟考试测试了下，感觉还可以，遇到没有匹配的可以自动停止，并且可以手动答题后重新开启自动答题模式，感觉很完美。再找到老铁的插件之前用了很多软件都不用，还把机会浪费了，哎，明天再正式答题试试~如果我们可以自己添加题库并上传我觉得这个云题库就完美了~~还是感谢您的无私分享，有爱的小插件~

**Comment by XTTGO** [comment]
如果我们可以自己添加题库并上传我觉得这个云题库就完美了~~还是感谢您的无私分享，有爱的小插件

**Comment by tyrad** [comment]
本来就是个小工具而已  不要太招摇了

五月应该是最后一期了

**Comment by ToQuery** [comment]
催更总决赛

**Comment by tyrad** [comment]
和五月题库是一样的吧
